export const main: string;
export const poster: string;
export const details: string;
export const title: string;
export const category: string;
export const yearAndDuration: string;
export const year: string;
export const duration: string;
export const description: string;
